version: "3.8"

services:
  krs_mysql:
    image: mysql:8.0
    container_name: krs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: krs
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  krs_backend:
    build:
      context: ./backend
    container_name: krs_backend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - krs_mysql

  krs_frontend:
    build:
      context: ./frontend
    container_name: krs_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - krs_backend

volumes:
  mysql_data:
