version: "3.8"

services:
  krs_mysql:
    image: mysql:8
    container_name: krs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: krs
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  krs_backend:
    build: ./backend
    container_name: krs_backend
    restart: always
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - krs_mysql
    command: >
      sh -c "composer install && php spark serve --host 0.0.0.0 --port 8000"

  krs_frontend:
    build: ./frontend
    container_name: krs_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - krs_backend
    command: >
      sh -c "composer install && php artisan key:generate && php artisan serve --host 0.0.0.0 --port 3000"
