version: "3.8"

services:
  krs_mysql:
    image: mysql:8
    container_name: krs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: krs
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
